#!/bin/bash
#
# update_ros_lib.sh
# Generate rosserial C++ headers from the latest OpenMower Docker image
# and update the local ros_lib directory while preserving STM32-specific files.
#
# Usage:
#   ./update_ros_lib.sh [docker_image]
#
# Default image: ghcr.io/clemenselflein/open_mower_ros:main
# For Mowgli-compatible: ghcr.io/nekraus/open_mower_ros_mowgli:Mowgli-compatible
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROS_LIB_DIR="${SCRIPT_DIR}/ros_lib"
BACKUP_DIR="${SCRIPT_DIR}/ros_lib_backup_$(date +%Y%m%d_%H%M%S)"
TEMP_DIR=$(mktemp -d)

# Docker image to use
DOCKER_IMAGE="${1:-ghcr.io/clemenselflein/open_mower_ros:main}"

# Files to preserve (STM32-specific, not generated by rosserial)
PRESERVE_FILES=(
    "STM32Hardware.h"
)

# Packages to generate headers for (custom OpenMower + Mowgli packages)
# Standard ROS packages (std_msgs, geometry_msgs, etc.) are generated automatically
CUSTOM_PACKAGES="mower_msgs xbot_msgs xesc_msgs mowgli"

cleanup() {
    echo "Cleaning up temporary files..."
    rm -rf "${TEMP_DIR}"
    # Remove container if it exists
    docker rm -f mowgli_roslib_gen 2>/dev/null || true
}
trap cleanup EXIT

echo "============================================"
echo "  Mowgli ros_lib Update Script"
echo "============================================"
echo ""
echo "Docker image: ${DOCKER_IMAGE}"
echo "Target dir:   ${ROS_LIB_DIR}"
echo ""

# Step 1: Pull the latest Docker image
echo "[1/6] Pulling latest Docker image..."
docker pull "${DOCKER_IMAGE}"

# Step 2: Generate rosserial headers inside the container
echo "[2/6] Generating rosserial C++ headers inside Docker container..."

docker run --rm --name mowgli_roslib_gen \
    --user root \
    -v "${TEMP_DIR}:/output" \
    "${DOCKER_IMAGE}" \
    bash -c '
        set -e
        source /opt/ros/noetic/setup.bash

        # Source the workspace if it exists
        for ws in /opt/open_mower_ros/devel/setup.bash \
                   /catkin_ws/devel/setup.bash \
                   /home/*/catkin_ws/devel/setup.bash \
                   /root/catkin_ws/devel/setup.bash; do
            if [ -f "$ws" ]; then
                echo "Sourcing workspace: $ws"
                source "$ws"
                break
            fi
        done

        # Install rosserial if not present
        if ! rospack find rosserial_arduino 2>/dev/null; then
            echo "Installing rosserial_arduino..."
            apt-get update -qq && apt-get install -y -qq ros-noetic-rosserial-arduino
        fi

        # List available message packages for debugging
        echo ""
        echo "Available custom packages:"
        for pkg in mower_msgs xbot_msgs xesc_msgs mowgli; do
            if rospack find "$pkg" 2>/dev/null; then
                echo "  [OK] $pkg -> $(rospack find $pkg)"
            else
                echo "  [--] $pkg not found"
            fi
        done
        echo ""

        # Generate all headers (including standard ROS msgs + custom packages)
        # Note: make_libraries.py creates a ros_lib/ subdirectory inside the output path
        echo "Running make_libraries.py..."
        rosrun rosserial_arduino make_libraries.py /output

        # Fix ownership so the host user can access the files
        chown -R '"$(id -u):$(id -g)"' /output/ros_lib

        echo ""
        echo "Generated packages:"
        ls -d /output/ros_lib/*/ 2>/dev/null | xargs -I{} basename {} | sort
        echo ""
        echo "Generation complete."
    '

# Check that generation was successful
if [ ! -d "${TEMP_DIR}/ros_lib" ]; then
    echo "ERROR: Header generation failed. No ros_lib directory created."
    exit 1
fi

# Step 3: Backup existing ros_lib
echo "[3/6] Backing up existing ros_lib to ${BACKUP_DIR}..."
cp -r "${ROS_LIB_DIR}" "${BACKUP_DIR}"

# Step 4: Preserve STM32-specific files
echo "[4/6] Preserving STM32-specific files..."
PRESERVE_DIR="${TEMP_DIR}/preserved"
mkdir -p "${PRESERVE_DIR}"
for f in "${PRESERVE_FILES[@]}"; do
    if [ -f "${ROS_LIB_DIR}/${f}" ]; then
        cp "${ROS_LIB_DIR}/${f}" "${PRESERVE_DIR}/${f}"
        echo "  Preserved: ${f}"
    fi
done

# Step 5: Replace ros_lib with newly generated headers
echo "[5/6] Replacing ros_lib with updated headers..."
rm -rf "${ROS_LIB_DIR}"
mv "${TEMP_DIR}/ros_lib" "${ROS_LIB_DIR}"

# Remove Arduino-specific hardware files
rm -f "${ROS_LIB_DIR}/ArduinoHardware.h"
rm -f "${ROS_LIB_DIR}/ArduinoTcpHardware.h"

# Step 6: Restore preserved files
echo "[6/6] Restoring STM32-specific files..."
for f in "${PRESERVE_FILES[@]}"; do
    if [ -f "${PRESERVE_DIR}/${f}" ]; then
        cp "${PRESERVE_DIR}/${f}" "${ROS_LIB_DIR}/${f}"
        echo "  Restored: ${f}"
    fi
done

echo ""
echo "============================================"
echo "  Update Complete!"
echo "============================================"
echo ""
echo "Backup at: ${BACKUP_DIR}"
echo ""

# Show what changed
echo "--- Changes summary ---"
echo ""
echo "New/Updated packages:"
ls -d "${ROS_LIB_DIR}"/*/ 2>/dev/null | xargs -I{} basename {} | sort
echo ""

# Show diff summary for custom packages
echo "--- Diff for custom message packages ---"
for pkg in mower_msgs xbot_msgs xesc_msgs mowgli; do
    if [ -d "${ROS_LIB_DIR}/${pkg}" ]; then
        echo ""
        echo "=== ${pkg} ==="
        if [ -d "${BACKUP_DIR}/${pkg}" ]; then
            diff -rq "${BACKUP_DIR}/${pkg}" "${ROS_LIB_DIR}/${pkg}" 2>/dev/null || true
        else
            echo "  NEW package (did not exist before)"
            ls "${ROS_LIB_DIR}/${pkg}/"
        fi
    fi
done

echo ""
echo "Next steps:"
echo "  1. Review the changes above"
echo "  2. Check cpp_main.cpp for any API changes in message fields"
echo "  3. Build the firmware to verify compatibility"
echo "  4. If issues, restore from: ${BACKUP_DIR}"
echo ""
