#!/usr/bin/env bash

# Ensure config files mounted as bind-mount *files* exist before compose runs.
# Docker creates a directory when the host path is missing, which breaks the
# container with "not a directory" errors.
ensure_default_configs() {
  local defaults="$REPO_DIR/docker/config"

  mkdir -p "$INSTALL_DIR/config/mqtt"
  mkdir -p "$INSTALL_DIR/config/mowgli"
  mkdir -p "$INSTALL_DIR/config/om"
  mkdir -p "$INSTALL_DIR/config/db"

  if [ ! -f "$INSTALL_DIR/config/mqtt/mosquitto.conf" ]; then
    cp "$defaults/mqtt/mosquitto.conf" "$INSTALL_DIR/config/mqtt/mosquitto.conf"
    info "Created default mosquitto.conf"
  fi

  if [ ! -f "$INSTALL_DIR/config/cyclonedds.xml" ]; then
    cp "$defaults/cyclonedds.xml" "$INSTALL_DIR/config/cyclonedds.xml"
    info "Created default cyclonedds.xml"
  fi
}

build_compose_stack() {
  COMPOSE_FILES=()

  COMPOSE_FILES+=("compose/docker-compose.base.yml")
  COMPOSE_FILES+=("compose/docker-compose.gui.yml")
  COMPOSE_FILES+=("compose/docker-compose.mqtt.yml")
  COMPOSE_FILES+=("compose/docker-compose.gps.yml")

  # Foxglove bridge is controlled via the ENABLE_FOXGLOVE env var passed
  # to the ROS2 container (see docker-compose.base.yml).  No separate
  # compose file is needed — the launch file starts/skips the node.

  if [[ "${LIDAR_ENABLED:-true}" == "true" && "${LIDAR_TYPE:-none}" != "none" ]]; then
    case "${LIDAR_TYPE:-}" in
      rplidar)
        COMPOSE_FILES+=("compose/docker-compose.lidar-rplidar.yml")
        ;;
      ldlidar)
        COMPOSE_FILES+=("compose/docker-compose.lidar-ldlidar.yml")
        ;;
      stl27l)
        COMPOSE_FILES+=("compose/docker-compose.lidar-stl27l.yml")
        ;;
      *)
        warn "Unknown LIDAR_TYPE: ${LIDAR_TYPE:-unset}"
        ;;
    esac
  fi

  [[ "${TFLUNA_FRONT_ENABLED:-false}" == "true" ]] && \
    COMPOSE_FILES+=("compose/docker-compose.tfluna-front.yml")

  [[ "${TFLUNA_EDGE_ENABLED:-false}" == "true" ]] && \
    COMPOSE_FILES+=("compose/docker-compose.tfluna-edge.yml")

  [[ "${ENABLE_MAVROS:-false}" == "true" ]] && \
    COMPOSE_FILES+=("compose/docker-compose.mavros.yml")

  [[ "${ENABLE_VESC:-false}" == "true" ]] && \
    COMPOSE_FILES+=("compose/docker-compose.vesc.yml")

  info "Compose stack:"
  for f in "${COMPOSE_FILES[@]}"; do
    echo "  - $f"
  done
}

write_compose_include() {
  # Write a top-level docker-compose.yaml that includes all selected compose files.
  # This allows bare "docker compose" commands from $INSTALL_DIR (used by helpers).
  local include_file="$INSTALL_DIR/docker-compose.yaml"

  {
    echo "# Auto-generated by mowglinext installer — do not edit manually"
    echo "# Re-run the installer to regenerate after changing hardware config"
    echo "include:"
    for f in "${COMPOSE_FILES[@]}"; do
      echo "  - $f"
    done
  } > "$include_file"

  info "Wrote $include_file"
}

run_compose_stack() {
  local args=()
  local f

  cd "$INSTALL_DIR" || return 1

  ensure_default_configs

  echo ""
  info "Selected compose files:"
  for f in "${COMPOSE_FILES[@]}"; do
    echo "  - $f"
    args+=(-f "$f")
  done
  echo ""

  write_compose_include

  info "Using env file: $INSTALL_DIR/.env"

  info "Pulling selected images..."
  docker compose --project-directory "$INSTALL_DIR" --env-file "$INSTALL_DIR/.env" "${args[@]}" pull

  echo ""
  info "Starting selected stack..."
  docker compose --project-directory "$INSTALL_DIR" --env-file "$INSTALL_DIR/.env" "${args[@]}" up -d

  echo ""
  info "Current containers:"
  docker compose --project-directory "$INSTALL_DIR" --env-file "$INSTALL_DIR/.env" "${args[@]}" ps
}