services:
  tfluna_front:
    container_name: mowgli-tfluna-front
    image: ${RANGE_IMAGE:-ghcr.io/...}
    network_mode: host
    privileged: true
    devices:
      - ${TFLUNA_FRONT_PORT}:/dev/tfluna_front
    restart: unless-stopped