
services:
  vesc:
    container_name: mowgli-vesc
    image: ${VESC_IMAGE}
    network_mode: host
    ipc: host
    privileged: true
    environment:
      <<: *ros2-env
      VESC_CAN_INTERFACE: ${VESC_CAN_INTERFACE:-can0}
    restart: unless-stopped